title: Dos-Analysis
description: Data portfolio — SQL → Excel → Power BI
logo: assets/images/profile_pic.jpg
show_downloads: True
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
url: https://dos-analysis.github.io
baseurl: /TikTok-Marketing-Campaign-Analysis>
