title: Dos-Analysis
description: Data portfolio — SQL → Excel → Power BI
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: true

# Required for project pages
url: "https://dos-analysis.github.io"
baseurl: "/TikTok-Marketing-Campaign-Analysis"
